### ISSUE TITLE
Allow full circle for heading

### ISSUE THREAD

**Issue by th-bu** [calibx/msfsdeck#105]
Currently the range for the heading knob is 0 .. 359.

If I want to fly more to the left while flying to 0 I have to disable heading, scroll all the way to the right and then enable heading again.

It would be nice if I could just go to the left from 0 to go to 359.

**Comment by th-bu** [comment]
And if you're at it can you change the min value for heading to 1 as there is no 0 heading in the game? It's 360 and then 1.

**Comment by calibx** [comment]
1.0.4 release with the fix

**Comment by th-bu** [comment]
Over the weekend someone using my fix said that this also is a problem in the airliner AP. I have already fixed this in my local version (still based on 1.0.3) so you probably have to add the fix there too.

Let me know if you want me to do another pull request.

**Comment by calibx** [comment]
Fixed for new release thank you !
