### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by BaconSarnie** [calibx/msfsdeck#107]
Everytime I try to install the plug in loupedeck live tells me the plug in has crashed
It asks me if I want to activate it, a box pops up telling me to wait that loupedeck has to be restarted, please wait
This sits there and does nothing, I eventually have to manually restart my loupedeck
Gone through this process numerous times and gotten no where

![image](https://user-images.githubusercontent.com/111691088/192999761-ebbe7b34-ffa6-45cc-9de9-79d4c7de69df.png)

**Comment by BaconSarnie** [comment]
![image](https://user-images.githubusercontent.com/111691088/193000986-8526bb32-07f9-4c83-9e01-99bff7425a12.png)

**Comment by calibx** [comment]
Hi, yes there is a problem during the first start of the plugin. But it will work without problem !
You can see it here : https://www.youtube.com/watch?v=Yu9msdHeTxk&ab_channel=SimHangerFlightSimulation

**Comment by calibx** [comment]
PR merged will be fixed in 1.0.5
