### ISSUE TITLE
No plugin icon in v 2.0.0

### ISSUE THREAD

**Issue by CalypteCreative** [calibx/msfsdeck#140]
Hi,

When I install or update msfsdeck to 2.0.0 the icon for MSFS disappears and I no longer can access MSFS features.

![Screenshot 2022-10-14 175440](https://user-images.githubusercontent.com/4442429/195889527-5e71c633-292c-4348-bb2c-676faa8376ec.png)

**Comment by RubiXKube** [comment]
I had the same, i thought it was my PC
I've totally remove loopedeck software, remove folder manually, and clean registry
and a fresh install resolve the issue

**Comment by calibx** [comment]
Should be fixed in 2.0.2 : https://github.com/calibx/msfsdeck/releases/tag/2.0.2
