### ISSUE TITLE
Plugin won't activate

### ISSUE THREAD

**Issue by Gabbalo** [calibx/msfsdeck#158]
Hi everyone,

I am struggeling to install the plugin successfully. 
After hitting "Install" in the marketplace, it all seems normal and installation is exited with a success message.
<img width="396" alt="image" src="https://user-images.githubusercontent.com/5897819/198870698-7a24438f-f172-4679-9810-22f95c9b1630.png">
However, in the plugin-window it tells me it was not activated due to a crash (it didn't crash during installation!) and therefore is not activated. I need to reinstall or aktivate it. 
<img width="570" alt="image" src="https://user-images.githubusercontent.com/5897819/198870708-ca043faa-6b78-4729-8110-6692a08accf9.png">
Reinstall is greyed out, and upon hitting activate plugin, the Plugin does not have a name anymore and the program stays in "activating" forever.
<img width="399" alt="image" src="https://user-images.githubusercontent.com/5897819/198870715-5a0ce6e5-534e-4caa-b4a8-3d3ec429b86d.png">

Firmware is 0.2.5, Software 5.3.1.14222 (both newest)

Any help available? =(

**Comment by calibx** [comment]
Hi,

The market plugin (1.0.0) is buggy :  there was a mistake in a classname so the UI doesn't detect it well.
Simply restart the ui and go the profile section to choose the MSFS Plugin.
The other solution is to use a more recent plugin release (2.1.0) for here.

**Comment by Gabbalo** [comment]
Yeah ... I'll probably use the newest from here then. Thank you :)
