### ISSUE TITLE
AP - Yaw Damper

### ISSUE THREAD

**Issue by JayCeeDC** [calibx/msfsdeck#161]
Hi,

A YD (Yaw Damper) toggle in the AP folder would be a nice feature!

Thanks!

**Comment by calibx** [comment]
Added in next release but I don't know how to test it :)

**Comment by RubiXKube** [comment]
You can test it with cessna CJ4 (Basic MSFS plane)
Start on a runaway and test it, you will have YD on PFD
https://prnt.sc/msLzYHHk83bz

**Comment by calibx** [comment]
Thank you !
![image](https://user-images.githubusercontent.com/17730126/200406658-663dc9a7-7e00-4c14-8d36-878e1968787c.png)
