### ISSUE TITLE
Use LD physical buttons to switch folders

### ISSUE THREAD

**Issue by JayCeeDC** [calibx/msfsdeck#164]
Hi,

Why not using the round physical LD buttons (1,2,3,...) to switch between AP, Lights,... folders?
This would save space on the touch screen for more functions.

Thanks!

**Comment by calibx** [comment]
Hi,
Great idea !
I will modify the default layout to map them.
But you can modify the default profile by drag/dropping folder on the physical buttons on your own

**Comment by JayCeeDC** [comment]
> Hi, Great idea ! I will modify the default layout to map them. But you can modify the default profile by drag/dropping folder on the physical buttons on your own

Excellent! Thank you.
I actually bought a LD 2 weeks ago only because of your msfs plugin! Will be happy to participate for ideas, testing, ....
