### ISSUE TITLE
Include WASM Module

### ISSUE THREAD

**Issue by calibx** [calibx/msfsdeck#173]
https://github.com/MobiFlight/MobiFlight-WASM-Module

**Comment by calibx** [comment]
Path to search : https://github.com/MobiFlight/MobiFlight-Connector/blob/main/MSFS2020-module/install-mobiflight-event-module.cmd
Cnx : https://github.com/MobiFlight/MobiFlight-Connector/tree/main/SimConnectMSFS

**Comment by ScottiSws** [comment]
Calibx,

Great LD implementation! I got your source and set up my own WASM module to access HVars and LVars. I can access things like the Managed vs. Selected modes of the Neos. Still, we're waiting on an SDK update ( roadmap 2023? ) to allow access to BVars so we can call the preset InputEvents. That or Asobo implements custom controller bindings for individual aircraft. Please let me know what your thoughts are.

 https://forums.flightsimulator.com/t/enhanced-api-to-access-all-aircraft-state-and-trigger-all-cockpit-functions/454608/188
