### ISSUE TITLE
NAV radio folder like COMs radio

### ISSUE THREAD

**Issue by Romulas67** [calibx/msfsdeck#186]
First up, great work calibx! I'll buy you a coffee.

Is it possible to code a NAV radio folder to match what has been done with the COMs radio folder?

**Comment by calibx** [comment]
Good idea !

**Comment by calibx** [comment]
Will try !

**Comment by calibx** [comment]
Nav folder is ready for next release !

**Comment by Romulas67** [comment]
Great news! And thanks in advance

**Comment by Romulas67** [comment]
Tested and its working Great!  Thanks again.
