### ISSUE TITLE
Loupedeck S : Custom Com Folder

### ISSUE THREAD

**Issue by Msanders1** [calibx/msfsdeck#187]
Dear, 

First of all , thanks for the great work you did . 
Thanks. 

Now I have the loupedeck S with 2 encoders.
I can use most of the functions and modify some functions or find a workaround for it . 

But the folders aren't adjustable.
Also the function inside the folder are hidden and not reusable. 
So I can't use the com page for instance.

Is there a way you can make a S version?
Or can you make the functions in the folder also available so I can modify it my self to use in my own adapted version. 

I hoop you can help. 

Greating Matthieu.

**Comment by calibx** [comment]
Hi,
Can you explain the problem with the folders ? They don't open ?
Except for the COM one, all other folder inputs are available as simple input /encoder

**Comment by Msanders1** [comment]
Thanks for the quick response.

Yes, the folder openes without any problems.

When I'm in the com folder I can only change the value of com 1 and com 2 before the decimal point and not after the decimal point. I only have two encoder buttons on the S version of the loupedeck .

I can't rearrange the functionality of the encoder buttons. 
Otherwise I would rearrange the encoder function so  I  can adjust only com 1, but then the number before and after the decimal point. And then a separate dail page to adjust com 2.

Indeed, the functions of the other folders are available as separate functions. But not the ones in the com folder.

I really would like to use the com page. This is the only function that doesn't work for the loupedeck S. 

So I was hoping that there would be a loupedeck S version of the profile. 

Greetings, Matthieu

**Comment by calibx** [comment]
Ok I understand better the problem.
Do you have an idea of the layout / action you would like for the COM folder ?

**Comment by calibx** [comment]
Ok I will try that. 
I don't know if I can detect the current device, if it is not possible I will create a special folder input for the S

**Comment by calibx** [comment]
Ok the first try is ready to be included in the next release but it is a blind test so I don't know the result

**Comment by Msanders1** [comment]
Thanks,
I will test the app this upcoming weekend and I give you a feedback.

Thanks for the work so far.

Matthieu

**Comment by Msanders1** [comment]
Dear Calibx.

Thank you very much for the adjustment.

COM1 on one touch screen is perfect.

Just the two rotary knobs. One is fine (COM1 x.) but the second is COM2 x. It would be great if your COM2 x. can change to COM1 .x

Like I said, I only have two dials.

Now I can't change the value after the comma yet.

And it would be nice if pressing the dragon button would swap between active and standby.

Then possibly a second page for COM 2. And then maybe the same for NAV.

Surely I will buy you a coffee.

Thank you ,
Matthieu

**Comment by calibx** [comment]
Hi, just received my S ...  I understand the mess I made :)
Will be fixed for the next release

**Comment by Msanders1** [comment]
Dear Calibx,

You doing a great job.
It's nice to hear you have your own Loupedeck S now.

T was hard to explain my issues.

Looking forward to the next update.

Thank you so much.

Matthieu.

**Comment by Msanders1** [comment]
Thanks for the adjustment.

Com works perfectly fine on the loupedeck S

Super thanks.

Matthew
