### ISSUE TITLE
Razer Stream Controller - problem

### ISSUE THREAD

**Issue by serdarqw** [calibx/msfsdeck#192]
Hi
I am using the Razer Stream Controller and I have a problem. The plugin is incompatible with the device. The .lplug4 file cannot be installed manually. Do you anticipate fixing the problem.
Regards
Jan

**Comment by calibx** [comment]
Hi,
The plugin should work since the 2.2.0 but I cannot include a default profile as I don't have a razor one.
You have to create your own profile : https://github.com/calibx/msfsdeck/discussions/154
