### ISSUE TITLE
Some basic items do not seem to work

### ISSUE THREAD

**Issue by smoothchat** [calibx/msfsdeck#204]
### Discussed in https://github.com/calibx/msfsdeck/discussions/203

<div type='discussions-op-text'>

<sup>Originally posted by **smoothchat** December 15, 2022</sup>
Thanks for making this excellent plugin available.

Just a couple of observations with v2.3.0.

Aircraft = C172 Classic

Parking Brakes - the indicator works (when toggled via the sim), however pressing the button appears to do nothing.

Pedestral Light - doesn’t appear to work.
CabinLight - doesn’t appear to work either. I think these require a “SET” event rather than a value change.

Instrument Lights - works, but you need to set Light_Potentiometer_3 to 100 otherwise, if the lights are turned down, they don’t illuminate on the button press

</div>

**Comment by calibx** [comment]
Hi,
The problem with lightd doesn't come from the plugin but it rely on the aircraft implementation.
For example the 3 lights works well with the 747 but not the C172.

I will fix the parking brakes as it seems that the old event doesn't work anymore
