### ISSUE TITLE
 No update ?

### ISSUE THREAD

**Issue by Msanders1** [calibx/msfsdeck#220]
dear calibx,

Have you stopped maintaining the mod???

Sanders

**Comment by calibx** [comment]
Hi,
No :) just lot of daily work on january.
I think febrary will be more compatible with the plugin dev

**Comment by MaciekMagura** [comment]
Good morning calibx :) What else do you plan to improve? Possibly add? Thx

**Comment by calibx** [comment]
The new release will add the NAV folder for the loupe S and a configurable toggle

**Comment by calibx** [comment]
The new update is here ! 3.0.0 (not all is included but it is a new release cycle)
