### ISSUE TITLE
Livedeck s not working

### ISSUE THREAD

**Issue by BuffaloBuck** [calibx/msfsdeck#252]
Hey , I've problems getting my loupedeck live s running with msfs. None of the buttons from the plugnin from  calibx are working. I think the point is the wasm module. I've done doing the wasm verifying and the mobiflight event module is showing up in dev mode in msfs. But in mobilflight i cant see the wasm module in the sim status.
In many youtube tutorials the plug in is loaded from the marketplace. But i cant seen t there and loaded it from github.

**Comment by Beetlecat** [comment]
Is this after the recent loupedeck software update?

**Comment by BuffaloBuck** [comment]
I just get the loupedeck aweek ago and so the software. So i think it must be the latest version

**Comment by calibx** [comment]
Yes there is a problem with the 6.x release of the loupedeck ui. I will try to fix this and publish bach the plugin to the market

**Comment by BuffaloBuck** [comment]
Hey, after i read about massive problems with the 6.0 update i downgraded to 5.9.1 and, look at that. It works fine :D

**Comment by rentasad** [comment]
Has anyone a link to an older Version for me?

**Comment by rentasad** [comment]
I found the link here
https://loupedeck.com/de/downloads/

**Comment by NJTravelerDH** [comment]
Thanks for your work on the loupedeck and MSFS 2020.
I updated my Loupedeck Live to 6.0. I installed Mobiflight 10.3.0. 
With MFSF running, I open Mobiflight and Modules in lower left corner states error "No Modules Found". Mobiflight tab Extras tab MSFS2020 tab Install WASM Module states "MobiFlight WASM Module is already installed and is up to date". And MobiFlight Modules tab at top which open Settings discusses boards and is blank. I found a 2nd Community Folder, and copied Mobiflight files to the MSFS2020 Community folder, re-opened MSFS, but there was no apparent changes. My MobiFlight sees all my peripherals, and the Loupedeck.  
MSFS 2020 Developer Mode shows 2 Mobi files; mobiflight which is unmounted and mobiflight-event module which is mounted. 
I tested MSFS with both a stock MSFS 2020 Cessna 172 (G1000) & an A2A PA24 Comanche 250.  Same error.
The Loupedeck does not show any values, which means to me there is no connection between the Loupedeck, MobiFlight, & MSFS.
Mobiflight Output and Input are both blank.
Simhanger suggests I check with Mobiflight.  MobiFlight suggests I check with the plugin developer,
I don't know how to get Mobi Output or Input.  I don't know how to mount the mobiflight or whether both are required.
Do you have any suggestions for me?
What should I do next?
Dave (in New Jersey)

**Comment by NJTravelerDH** [comment]
Update on Oct. 12, '24: Dowgrade to 5.9.1.19364 -- No Change, Still Need Help
Loupedeck:
COM & NAV knobs do not work
None of the displays have values (with MSFS 2020, Cessna 172 (G1000) running on the runway ready for takeoff)
MobiFlight:
Modules error: “no modules found”
WASM module installed and up-to-date
All peripherals recognized
Input / Output are blank
Configured Modules is “none”

**Comment by NJTravelerDH** [comment]
Well, I seem to be dependent on a solution from this site.  Simhanger, Mobiflight, Loupedeck all state they do not have a solution for me, and that I should request help from the plugin author.  So, Calibx, or anyone else, if you can offer a suggestion, I would appreciate it.  I think the above two posts fully describes my status.  I'll just emphasize I downgraded to 5.9.1 and MobiFlight has been upgraded to 10.4.0.  But nothing changed - still no values on the Loupedeck (and my custom key input for views does work).  Dave in NJ

**Comment by BenBroadcast** [comment]
@calibx there are news for a fix? :) thx for your work

**Comment by calibx** [comment]
A little update : 
- the main problem here is the compatibility with 6.0 so please follow that issue #254 for updates
- @NJTravelerDH :  please open a discussion thread about your problem to discuss it.
