### ISSUE TITLE
Knob Click dont work

### ISSUE THREAD

**Issue by DivingEye** [calibx/msfsdeck#77]
Hello i need to can activate the managed or unmanaged speed and altitude
![2022-03-03 22_48_04-Microsoft Flight Simulator - 1 23 12 0](https://user-images.githubusercontent.com/48368602/156658493-b37e5ec0-8f00-449b-b99e-fadacf35ee8d.png)

**Comment by calibx** [comment]
Ok I will replace it !

**Comment by calibx** [comment]
Fixed in rc11
