### ISSUE TITLE
AP Altitude failure

### ISSUE THREAD

**Issue by DivingEye** [calibx/msfsdeck#84]
I cant setting more than 20.000 FT over the Loupedeck Altitude Knob

**Comment by calibx** [comment]
Hi, is 20.000 FT a limit for AP ?

**Comment by DivingEye** [comment]
No if i turning manually over the knob in the cockpit i can set 36000 and more and the AP do it

**Comment by calibx** [comment]
Ok in a a320 Néo I can set 99900 => fixed for the next release

**Comment by DivingEye** [comment]
thank you very much
