### ISSUE TITLE
Auto Taxi Button

### ISSUE THREAD

**Issue by DivingEye** [calibx/msfsdeck#90]
Hallo Thanks for the Update but i am missing the AutoTaxi Button

**Comment by calibx** [comment]
Hi, it will come back in the next release

**Comment by calibx** [comment]
Ok the code is merged in the 1.0.1 => release tomorrow

**Comment by DivingEye** [comment]
hello calibx can you explain me how u code the loupedeck with msfs maybe i can help you for develop

Kovačević Toni

Salesforce -Ranger
Projectmanager
Kryon Dev
Sharepoint Dev

Neureutherstr. 18
80799 München
Germany

mob:         +49 170 8 111 521
***@***.***:      ***@***.***
linkedin:    linkedin.com/in/toni-kovacevic
facebook: facebook.com/kovacevic.toni
________________________________
Von: calibx ***@***.***>
Gesendet: Saturday, May 7, 2022 12:59:56 PM
An: calibx/msfsdeck ***@***.***>
Cc: Toni Kovacevic ***@***.***>; Author ***@***.***>
Betreff: Re: [calibx/msfsdeck] Auto Taxi Button (Issue #90)


Ok the code is merged in the 1.0.1 => release tomorrow

**Comment by calibx** [comment]
I'ts very easy, you can clone my repo, import it in Visual Studio,  and launch it.
After that all is in the sdk : 
reading from msfs with variables : https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_AutopilotAssistant_Variables.htm
writing with events : https://docs.flightsimulator.com/html/Programming_Tools/Event_IDs/Aircraft_Autopilot_Flight_Assist_Events.htm

In my plugin all the MSFS logic in the SimConnect class.
It's a mess but cleaning is in progress

**Comment by DivingEye** [comment]
Hallo Calibx,

thanks and how you create a new release of .lplug4 if you make changes?

Thanks

Von: calibx ***@***.***>
Gesendet: Samstag, 7. Mai 2022 13:14
An: calibx/msfsdeck ***@***.***>
Cc: Toni Kovacevic ***@***.***>; Author ***@***.***>
Betreff: Re: [calibx/msfsdeck] Auto Taxi Button (Issue #90)


I'ts very easy, you can clone my repo, import it in Visual Studio, and launch it.
After that all is in the sdk :
reading from msfs with variables : https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_AutopilotAssistant_Variables.htm
writing with events : https://docs.flightsimulator.com/html/Programming_Tools/Event_IDs/Aircraft_Autopilot_Flight_Assist_Events.htm

In my plugin all the MSFS logic in the SimConnect class.
It's a mess but cleaning is in progress

**Comment by calibx** [comment]
Simply configure your inputs in the UI then export the profil from the 3 dots menu in the profil : 
![image](https://user-images.githubusercontent.com/17730126/167257366-fec9f6c1-72d3-4622-a0bd-ff43012dd472.png)
![image](https://user-images.githubusercontent.com/17730126/167257355-875e3386-89dc-4693-b107-03c78ae12c0b.png)
![image](https://user-images.githubusercontent.com/17730126/167257374-b4065a88-5220-4f97-bc90-34bdc449d43b.png)

There is a default profil bundled in the plugin.

**Comment by calibx** [comment]
Autotaxi is back ! https://github.com/calibx/msfsdeck/releases/tag/1.0.0.1

**Comment by DivingEye** [comment]
[Image.jpeg]
thanks very much 😎👍💪 how you create this file?

Kovačević Toni

Salesforce -Ranger
Projectmanager
Kryon Dev
Sharepoint Dev

Neureutherstr. 18
80799 München
Germany

mob:         +49 170 8 111 521
***@***.***:      ***@***.***
linkedin:    linkedin.com/in/toni-kovacevic
facebook: facebook.com/kovacevic.toni
________________________________
Von: calibx ***@***.***>
Gesendet: Sunday, May 8, 2022 9:08:53 PM
An: calibx/msfsdeck ***@***.***>
Cc: Toni Kovacevic ***@***.***>; Author ***@***.***>
Betreff: Re: [calibx/msfsdeck] Auto Taxi Button (Issue #90)


Autotaxi is back ! https://github.com/calibx/msfsdeck/releases/tag/1.0.0.1
