### ISSUE TITLE
Set Radio Frequencies

### ISSUE THREAD

**Issue by airlinetycoon02** [calibx/msfsdeck#98]
Is there any way to set COM frequencies into the Radio panel?

**Comment by calibx** [comment]
Yes it is possible : https://docs.flightsimulator.com/html/Programming_Tools/Event_IDs/Aircraft_Radio_Navigation_Events.htm

Do you have an idea of a layout ? Encoders, inputs, actions ?

**Comment by airlinetycoon02** [comment]
yes, I have.
It would be cool to see the active frequency and the standby frequency.
the active frequency should only be visible, change stby frequency.
It would be great if you could turn in the digits before the decimal point with the left knob and the digits after the decimal point with one of the right knobs. 
When you press one of the knobs, you should be able to switch between active and stby frequency.

**Comment by calibx** [comment]
okay will look at that tomorow

**Comment by calibx** [comment]
Freq BCD encoded is a hell... Just found how to fallback to Hz. Hope to release a beta this week

**Comment by airlinetycoon02** [comment]
Thanks a lot!!! Hope it works

**Comment by calibx** [comment]
Hi the test release for UX validation is ready : https://github.com/calibx/msfsdeck/releases/tag/1.0.1
If all is right, I will add COM2 &3 in the next release 
Enjoy !

**Comment by devpaw-de** [comment]
Hi, thanks for adding this. Just what I was looking for. 
A quick remark for more realistic behavior: Increasing the value after the decimal point above .999 (or decreasing below .000) usually does not affect the value before the decimal. At least on the A320 and I think on the 737 as well, I'm not sure if that's the case on all airplanes.

![com](https://user-images.githubusercontent.com/68090595/176256217-afca5dca-7be6-4775-ac70-6a6b5b96d1f4.gif)

**Comment by calibx** [comment]
Hi, I will try to fix both today (was sick last week)

**Comment by calibx** [comment]
The new release is available : https://github.com/calibx/msfsdeck/releases/tag/1.0.2

**Comment by airlinetycoon02** [comment]
Wow!
Great work. Many Thanks!!

**Comment by devpaw-de** [comment]
Thanks for the update, looks great now. But the encoding of the frequency still does not behave like in the aircraft.

If you take another look at the Gif I posted before: The value after the decimal point does roll over from .995 to .000 (and reversed). It doesn't stop there. It just does not in-/decrease the value before the decimal point.

> ![com](https://user-images.githubusercontent.com/68090595/176256217-afca5dca-7be6-4775-ac70-6a6b5b96d1f4.gif)

**Comment by calibx** [comment]
You right, didn't notice the second point ... 1.0.3 is up !

**Comment by devpaw-de** [comment]
Great. Thank you!

**Comment by airlinetycoon02** [comment]
> You're right, didn't notice the second point ... 1.0.3 is up !

Thanks!!
What´s the next one? Nav-Radios and Transponder?

**Comment by calibx** [comment]
Yes, I will add com 2 tomorrow and close this issue, feel free to open new one for Nav radio or transponder

**Comment by airlinetycoon02** [comment]
Great, thanx!

**Comment by devpaw-de** [comment]
> Yes, I will add com 2 tomorrow and close this issue, feel free to open new one for Nav radio or transponder

Nice. Btw, I just noticed swapping active and standby freq is not possible by pushing the fractional encoder. Only the integer encoder swaps.

**Comment by calibx** [comment]
oh ... It seems that I have forget something :p
Will fix it this weekend

**Comment by calibx** [comment]
Ok it seems that the folder API evolve between 5.2 an 5.3 in LoupeDeck, will have to read the Loupe Wiki ....
Fix this week I hope

**Comment by calibx** [comment]
Ok the problem came from a deprecated api in LoupeDeck => fix merged for next release
